### ISSUE TITLE
Designing network for brain servers.

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/BrainCaffe#2]
Need to add another lan card (PCI-based) to the master server.
This server will be connected to 4 slaves via a local network (with a switch hub). 

Q. Which lan card is going to work well with our HP servers and Ubuntu 16.04.1?

**Comment by Hahnnz** [comment]
I do not know exactly what we will use.
which we use what kind of network? closed one? or opened one?

**Comment by Hahnnz** [comment]
For Closed Network on Brain server, MasterServer and Slaves, This len card should work for it.
[PX1000 PCI-Express LAN CARD](http://storefarm.naver.com/finecom/products/304649851?NaPm=ct%3Divhyul0o%7Cci%3De3285844d1f08c7bc780874d417351de5c449bd0%7Ctr%3Dslc%7Csn%3D257142%7Cic%3D%7Chk%3D18553b81100443ed572c12d95cf4a2567705438f) is represented that can support lunux, and includes realtek chip that means support realtek len card driver. interface is also PCI, so i think this is what we wanna find for connecting. so please Check this card and [driver](http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=14&PFid=6&Level=5&Conn=4&DownTypeID=3&GetDown=false)

**Comment by ys7yoo** [comment]
Ordered the lan card.
