### ISSUE TITLE
[ToDo] to update to use Caffe RC5

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/BrainCaffe#4]
Caffe was updated to RC5 on Feb 21 2017.
Let's update it to use the newest version.

**Comment by Hahnnz** [comment]
Yes Sir! I will update Caffe that i use
And I'm keeping the deepmaster and deepslaves. prof. hwang helps me to keep those 5 computors.
(So it will be used for parallel computing studying.) But there is no allowed accesss port to servers.
Do you have any good server to start researching and study Caffe and tensorflow? And I also want to change and upgrade this repository with resetting all of codes.

**Comment by ys7yoo** [comment]
It's done.
Use cprc5.sh for RC5
